### ISSUE TITLE
serv00服务器重启后失效

### ISSUE THREAD

**Issue by ggrreeeedd** [RayWangQvQ/sing-box-installer#11]
需要手动重启，如何实现进程守护以及重启后自动启动

**Comment by leungyiuhoi** [comment]
我也是一样，在serv00如何添加cron jobs改善该问题

**Comment by RayWangQvQ** [comment]
```
@reboot cd /home/<你名字>/sing-box && chmod +x ./data/entry.sh && ./data/entry.sh $PWD/data true
```

**Comment by ggrreeeedd** [comment]
./data/entry.sh: linia 23: sing-box: nie znaleziono polecenia

**Comment by ggrreeeedd** [comment]
sing-box/data/entry.sh: linia 16: $1: nieustawiona zmienna  运行entry.sh提示未设置变量

**Comment by leungyiuhoi** [comment]
cron jobs问题已经解决了，一个月都没有断线，谢谢！！！

**Comment by leungyiuhoi** [comment]
> ```
> @reboot cd /home/<你名字>/sing-box && chmod +x ./data/entry.sh && ./data/entry.sh $PWD/data true
> ```
cron jobs问题已经解决了，一个月都没有断线，谢谢！！！
