### ISSUE TITLE
sing-box-installer

### ISSUE THREAD

**Issue by jackszb** [RayWangQvQ/sing-box-installer#7]
大佬，一键脚本运行之后什么都没有啊

**Comment by bigm0re** [comment]
我有这个报错，不知道是差点什么插件吗
: invalid option 2: set: -
set: usage: set [-abefhkmnptuvxBCHP] [-o option-name] [--] [arg ...]
: invalid option 3: set: -
set: usage: set [-abefhkmnptuvxBCHP] [-o option-name] [--] [arg ...]
: invalid option nameet: pipefail
/dev/fd/63: line 5: $'\r': command not found
: ambiguous redirect1
/dev/fd/63: line 25: syntax error near unexpected token `$'{\r''

**Comment by RayWangQvQ** [comment]
需要日志排查
