### ISSUE TITLE
能不能套cf

### ISSUE THREAD

**Issue by darkrain88** [RayWangQvQ/sing-box-installer#9]
serv00 上面 建了一个web proxy， cf 开了小黄云。

连不上， -1ms 

有没有什么建议

**Comment by RayWangQvQ** [comment]
可以套CF的CDN，需要在CF做端口转发，只要端口跟web proxy不冲突就行

**Comment by tsinit2001** [comment]
> 可以套CF的CDN，需要在CF做端口转发，只要端口跟web proxy不冲突就行

小白求一下這步的操作教程。。。多謝啦~
